import mongoose from "mongoose";

const becomeAMentorSchema = new mongoose.Schema(
  {
    mentorImage: {
      type: String,
      required: [true, "Mentor image is a required field"],
    },
    mentorName: {
      type: String,
      required: [true, "Mentor Name is a required field"],
    },
    mentorGender: {
      type: String,
      enum: ["M", "F"],
      required: [true, "Mentor Gender is a required field"],
    },
    mentorFaculty: {
      type: String,
      required: [true, "Mentor Faculty is a required field"],
    },
    mentorPhoneNo: {
      type: String,
      required: [true, "Phone Number is a required field"],
      unique: true,
      match: [/^\d{10}$/, "Phone number must be of 10 digits"],
    },
    mentorFbProfileLink: {
      type: String,
      required: [true, "Mentor fb probile link is a required field"],
    },
    mentorEmail: {
      type: String,
      required: [true, "Mentor Email is a required field"],
      lowercase: true,
      unique: true,
      match: [/^\S+@\S+\.\S+$/, "Please enter a valid email address"],
    },
    collegeImage: {
      type: String,
      required: [true, "College Image is a required field"],
    },
    collegeName: {
      type: String,
      required: [true, "College Name is a required field"],
    },
    collegeDistrict: {
      type: String,
      enum: [
        "Achham",
        "Arghakhanchi",
        "Baglung",
        "Baitadi",
        "Bajhang",
        "Bajura",
        "Banke",
        "Bara",
        "Bardiya",
        "Bhaktapur",
        "Bhojpur",
        "Chitwan",
        "Dadeldhura",
        "Dailekh",
        "Dang",
        "Darchula",
        "Dhading",
        "Dhankuta",
        "Dhanusha",
        "Dolakha",
        "Dolpa",
        "Doti",
        "Eastern Rukum",
        "Gorkha",
        "Gulmi",
        "Humla",
        "Ilam",
        "Jajarkot",
        "Jhapa",
        "Jumla",
        "Kailali",
        "Kalikot",
        "Kanchanpur",
        "Kapilvastu",
        "Kaski",
        "Kathmandu",
        "Kavrepalanchok",
        "Khotang",
        "Lalitpur",
        "Lamjung",
        "Mahottari",
        "Makwanpur",
        "Manang",
        "Morang",
        "Mugu",
        "Mustang",
        "Myagdi",
        "Nawalparasi East",
        "Nawalparasi West",
        "Nuwakot",
        "Okhaldhunga",
        "Palpa",
        "Panchthar",
        "Parbat",
        "Parsa",
        "Pyuthan",
        "Ramechhap",
        "Rasuwa",
        "Rautahat",
        "Rolpa",
        "Rukum East",
        "Rukum West",
        "Rupandehi",
        "Salyan",
        "Sankhuwasabha",
        "Saptari",
        "Sarlahi",
        "Sindhuli",
        "Sindhupalchok",
        "Siraha",
        "Solukhumbu",
        "Sunsari",
        "Surkhet",
        "Syangja",
        "Tanahun",
        "Taplejung",
        "Tehrathum",
        "Udayapur",
      ],
      required: [true, "College District is a required field"],
    },
    collegeLevels: [
      {
        type: String,
        required: [true, "College Levels is a required field"],
      },
    ],
    collegeFaculties: [
      {
        type: String,
        required: [true, "College Faculties is a required field"],
      },
    ],
    collegeWebsiteLink: {
      type: String,
      required: [true, "College Website Link is a required field"],
    },
  },
  { timestamps: true }
);

export const BecomeAMentor = mongoose.model(
  "BecomeAMentor",
  becomeAMentorSchema
);
