import mongoose from "mongoose";

const clzInfoSchema = new mongoose.Schema(
  {
    imageUrl: {
      type: String,
      required: [true, "College image URL is a required field"],
    },
    name: {
      type: String,
      required: [true, "College Name is a required field"],
    },
    district: {
      type: String,
      enum: [
        "Achham",
        "Arghakhanchi",
        "Baglung",
        "Baitadi",
        "Bajhang",
        "Bajura",
        "Banke",
        "Bara",
        "Bardiya",
        "Bhaktapur",
        "Bhojpur",
        "Chitwan",
        "Dadeldhura",
        "Dailekh",
        "Dang",
        "Darchula",
        "Dhading",
        "Dhankuta",
        "Dhanusha",
        "Dolakha",
        "Dolpa",
        "Doti",
        "Eastern Rukum",
        "Gorkha",
        "Gulmi",
        "Humla",
        "Ilam",
        "Jajarkot",
        "Jhapa",
        "Jumla",
        "Kailali",
        "Kalikot",
        "Kanchanpur",
        "Kapilvastu",
        "Kaski",
        "Kathmandu",
        "Kavrepalanchok",
        "Khotang",
        "Lalitpur",
        "Lamjung",
        "Mahottari",
        "Makwanpur",
        "Manang",
        "Morang",
        "Mugu",
        "Mustang",
        "Myagdi",
        "Nawalparasi East",
        "Nawalparasi West",
        "Nuwakot",
        "Okhaldhunga",
        "Palpa",
        "Panchthar",
        "Parbat",
        "Parsa",
        "Pyuthan",
        "Ramechhap",
        "Rasuwa",
        "Rautahat",
        "Rolpa",
        "Rukum East",
        "Rukum West",
        "Rupandehi",
        "Salyan",
        "Sankhuwasabha",
        "Saptari",
        "Sarlahi",
        "Sindhuli",
        "Sindhupalchok",
        "Siraha",
        "Solukhumbu",
        "Sunsari",
        "Surkhet",
        "Syangja",
        "Tanahun",
        "Taplejung",
        "Tehrathum",
        "Udayapur",
      ],
      required: [true, "District is a required field"],
    },
    levels: [
      {
        type: String,
        required: [true, "Levels is a required field"],
      },
    ],
    faculties: [
      {
        type: String,
        required: [true, "Faculties is a required field"],
      },
    ],
    websiteLink: {
      type: String,
      required: [true, "Website Link is a required field"],
    },
  },
  { timestamps: true }
);

export const ClzInfo = mongoose.model("ClzInfo", clzInfoSchema);
